# Generated by Django 5.2.7 on 2025-10-17 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="user",
            new_name="AppUser",
        ),
    ]
