# Generated by Django 5.2.7 on 2025-10-19 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formapp", "0002_rename_user_appuser"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appuser",
            old_name="Email",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="appuser",
            old_name="FullName",
            new_name="full_name",
        ),
    ]
